name: EMA 15m Scanner

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          ACCESS_TOKEN: ${{ secrets.DHAN_ACCESS_TOKEN }}
          CLIENT_ID: ${{ secrets.DHAN_CLIENT_ID }}
          
